#Database type, either sqlite or mysql
databasetype: sqlite
table-prefix: rpen_

#MySQL Connection settings, only needed when databasetype is set to mysql
mysql:
  host: localhost
  user: root
  password: 1234
  database: minecraft
  port: 3306

#Debug
debug: false

#ChatSettings
chatEnabled: true
rpRange: 25
whisperRange: 3
shoutRange: 50
logOOC: true
logRP: true

#MaxAge for if nothing is defined at the race:
MaxAge: 75
#Races
Races:
  Human:
    Color: BROWN
    MaxAge: 100
    Plural: Humans
  Elf:
    Color: WHITE
    MaxAge: 1000
    Plural: Elves
  Makiuras:
    Color: YELLOW
    MaxAge: 100
    Plural: Makiuras
  Fomuri:
    Color: PURPLE
    MaxAge: 150
    Plural: Fomuri
  Syltyr:
    Color: BLUE
    MaxAge: 1000
    Plural: Syltyr
  Sarfnydd:
    Color: GREEN
    MaxAge: 50
    Plural: Sarf
#Nations
Nations:
  Humanity:
    spawnX: 0
    spawnY: 0
    spawnZ: 0
    spawnYaw: 0
    spawnPitch: 0
    spawnWorld: world
    
# Speed in block per second for birds
speed: 5

#Max for countdown and rolls
maxRoll: 1000
maxCountdown: 20

#The cooldown in-between card changes in seconds
cardCooldown: 600

#Player health (20 is one full row of hearts and the default value)
playerHealth: 20

# What language messages are sent in
language: en_us